#!/usr/bin/env python

import shutil
from pathlib import Path

from pystac import CatalogType

import stactools.global_mangrove_watch.stac

root = Path(__file__).parents[1]
examples = root / "examples"

collection = stactools.global_mangrove_watch.stac.create_collection()
item = stactools.global_mangrove_watch.stac.create_item(
    cog_asset_href=str(root / "tests" / "data" / "GMW_N26W082_2020_v3.tif"),
    change_asset_href=str(
        root / "tests" / "data" / "GMW_N26W082_chng_f1996_t2020_v3.tif"
    ),
)
collection.add_item(item)
collection.normalize_hrefs(str(examples))
collection.make_all_asset_hrefs_relative()
if examples.exists():
    shutil.rmtree(examples)
    examples.mkdir()
collection.save(CatalogType.SELF_CONTAINED)
